const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "Get A Pet API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
    {
      name: "Pet",
      description: "Endpoints",
    },
  ],
  definitions: {
    User: {
      name: "Felipe Fardo",
      email: "felipe.fardo@hotmail.com.br",
      phone: "(54) 99705-2867",
    },
    Pet: {
      name: "sahaszha",
      age: 2,
      weight: 2,
      color: "Branco",
      images: ["168340994472015.jpg", "168340994473050.jpg"],
      available: false,
      user: {
        _id: "6455131fc02d8b931f45a15d",
        name: "Felipe Fardo",
        phone: "54997052867",
      },
      adopter: {
        _id: "64553caf51dd01fbc0552299",
        name: "Mario",
      },
    },
    Register: {
      name: "Felipe Fardo",
      $email: "felipe.fardo@hotmail.com.br",
      $phone: "(54) 99705-2867",
      $password: "senha123",
      $confirmpassword: "senha123",
    },
    Login: {
      $email: "felipe.fardo@hotmail.com.br",
      $password: "senha123",
    },
    EditUser: {
      $name: "Felipe Fardo",
      $email: "felipe.fardo@hotmail.com.br",
      $phone: "(54) 99705-2867",
      password: "senha123",
      confirmpassword: "senha123",
      image: "jpg / png",
    },
    CreateAPet: {
      $name: "Pipoca",
      $age: 3,
      $weight: 12.3,
      $color: "Mesclado",
    },
    UpdateAPet: {
      $name: "Pipoca",
      $age: 4,
      $weight: 11,
      $color: "Mesclado",
    },
  },
};
const endpointsFiles = ["./index.js"];

const outputFile = "./swagger_output.json";
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./index.js");
});
